## Практическое задание

В файле water.txt представлено 61 наблюдение. Каждое наблюдение – город в
Англии и Уэльсе. Города дополнительно поделены на северные и южные. Для
каждого города известны средняя годовая смертность на 100000 населения (по
данным 1958–1964) и концентрация кальция в питьевой воде (в частях на
миллион). Чем выше концентрация кальция, тем жёстче вода.

In [10]:
import pandas as pd

df = pd.read_csv('14water.txt', sep = '\t')
print(df.head())

  location        tow  mortalit  hardness
0     Sout        Bat       124       105
1     Nort  Birkenhea       166        17
2     Sout  Birmingha       146         5
3     Nort   Blackbur       180        14
4     Nort   Blackpoo       160        18

In [11]:
south_df = df.query("location == 'Sout'")
south_df.describe()[['mortalit', 'hardness']]

         mortalit    hardness
count   26.000000   26.000000
mean   137.076923   69.769231
std     14.053962   40.360682
min    109.000000    5.000000
25%    125.250000   40.250000
50%    135.500000   75.500000
75%    148.000000   99.750000
max    162.000000  138.000000

In [12]:
north_df = df.query("location == 'Nort'")
north_df.describe()[['mortalit', 'hardness']]

         mortalit   hardness
count   35.000000  35.000000
mean   162.857143  30.400000
std     13.760863  26.134494
min    137.000000   6.000000
25%    155.000000  12.500000
50%    163.000000  17.000000
75%    171.500000  44.000000
max    198.000000  94.000000

Южные города характеризуются более низкой средней смертностью и заметно более высокой средней жёсткостью воды. Северные города, напротив, демонстрируют повышенный уровень смертности и более мягкую воду.

2) Постройте 95% доверительные интервалы для средней годовой смертности по
всем южным и северным городам. Отличаются ли границы интервалов?

In [13]:
from statsmodels.stats.weightstats import _tconfint_generic
import numpy as np

def mean_ci(series):
    n = series.shape[0]
    m = series.mean()
    se = series.std(ddof=1) / np.sqrt(n)
    return _tconfint_generic(m, se, n - 1, alpha=0.05/2, alternative='two-sided')

ci_south_mort = mean_ci(south_df['mortalit'])
ci_north_mort = mean_ci(north_df['mortalit'])

print( "95% interval south:", ci_south_mort)
print( "95% interval north:", ci_north_mort)

95% interval south: (130.50443969856775, 143.64940645527838)
95% interval north: (157.40251802672898, 168.31176768755674)

Интервалы практически не пересекаются: диапазон смертности на Севере полностью смещён вверх относительно Южных городов. Это означает статистически значимое отличие средних уровней смертности.

Постройте 95% доверительные интервалы для средней концентрации кальция в
питьевой воде для южных и северных городов. Отличаются ли границы
интервалов?

In [14]:
ci_south_hard = mean_ci(south_df['hardness'])
ci_north_hard = mean_ci(north_df['hardness'])


print( "95% interval south:", ci_south_hard)
print( "95% interval north:", ci_north_hard)

95% interval south: (50.894132785192504, 88.64432875326904)
95% interval north: (20.040630758135407, 40.75936924186459)

Интервальные оценки концентрации кальция в воде существенно различаются. Южные города имеют значительно более высокую жёсткость воды, различие статистически значимо.

Анализ данных показывает две ключевые закономерности:
1) Смертность в северных городах стабильно выше, что подтверждается как описательными статистиками, так и доверительными интервалами.
2) Концентрация кальция в питьевой воде значительно выше в южных городах.